/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-NEXRAN-IEs"
 * 	found in "/home/vikas/srslte-ric/srsenb/src/ric/messages/asn1/e2sm-nexran-v01.00.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example -fno-include-deps -fincludes-quoted -D /home/vikas/srslte-ric/build/srsenb/src/ric/messages/E2SM-NEXRAN/`
 */

#ifndef	_E2SM_NEXRAN_E2SM_NexRAN_ControlMessage_Id_H_
#define	_E2SM_NEXRAN_E2SM_NexRAN_ControlMessage_Id_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum E2SM_NEXRAN_E2SM_NexRAN_ControlMessage_Id {
	E2SM_NEXRAN_E2SM_NexRAN_ControlMessage_Id_sliceConfigRequest	= 0,
	E2SM_NEXRAN_E2SM_NexRAN_ControlMessage_Id_sliceDeleteRequest	= 1,
	E2SM_NEXRAN_E2SM_NexRAN_ControlMessage_Id_sliceStatusRequest	= 2,
	E2SM_NEXRAN_E2SM_NexRAN_ControlMessage_Id_sliceUeBindRequest	= 3,
	E2SM_NEXRAN_E2SM_NexRAN_ControlMessage_Id_sliceUeUnbindRequest	= 4,
	E2SM_NEXRAN_E2SM_NexRAN_ControlMessage_Id_sliceUeBindingReport	= 5
	/*
	 * Enumeration is extensible
	 */
} e_E2SM_NEXRAN_E2SM_NexRAN_ControlMessage_Id;

/* E2SM_NEXRAN_E2SM-NexRAN-ControlMessage-Id */
typedef long	 E2SM_NEXRAN_E2SM_NexRAN_ControlMessage_Id_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_E2SM_NEXRAN_E2SM_NexRAN_ControlMessage_Id_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_E2SM_NEXRAN_E2SM_NexRAN_ControlMessage_Id;
extern const asn_INTEGER_specifics_t asn_SPC_E2SM_NEXRAN_E2SM_NexRAN_ControlMessage_Id_specs_1;
asn_struct_free_f E2SM_NEXRAN_E2SM_NexRAN_ControlMessage_Id_free;
asn_struct_print_f E2SM_NEXRAN_E2SM_NexRAN_ControlMessage_Id_print;
asn_constr_check_f E2SM_NEXRAN_E2SM_NexRAN_ControlMessage_Id_constraint;
ber_type_decoder_f E2SM_NEXRAN_E2SM_NexRAN_ControlMessage_Id_decode_ber;
der_type_encoder_f E2SM_NEXRAN_E2SM_NexRAN_ControlMessage_Id_encode_der;
xer_type_decoder_f E2SM_NEXRAN_E2SM_NexRAN_ControlMessage_Id_decode_xer;
xer_type_encoder_f E2SM_NEXRAN_E2SM_NexRAN_ControlMessage_Id_encode_xer;
per_type_decoder_f E2SM_NEXRAN_E2SM_NexRAN_ControlMessage_Id_decode_uper;
per_type_encoder_f E2SM_NEXRAN_E2SM_NexRAN_ControlMessage_Id_encode_uper;
per_type_decoder_f E2SM_NEXRAN_E2SM_NexRAN_ControlMessage_Id_decode_aper;
per_type_encoder_f E2SM_NEXRAN_E2SM_NexRAN_ControlMessage_Id_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _E2SM_NEXRAN_E2SM_NexRAN_ControlMessage_Id_H_ */
#include "asn_internal.h"
