/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 */

#ifndef _E2SM_NEXRAN_ASN_CONSTANT_H
#define _E2SM_NEXRAN_ASN_CONSTANT_H

#ifdef __cplusplus
extern "C" {
#endif

#define E2SM_NEXRAN_maxOfSlices (16)
#define E2SM_NEXRAN_maxOfUes (256)


#ifdef __cplusplus
}
#endif

#endif /* _E2SM_NEXRAN_ASN_CONSTANT_H */
