/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-NEXRAN-IEs"
 * 	found in "/home/vikas/srslte-ric/srsenb/src/ric/messages/asn1/e2sm-nexran-v01.00.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example -fno-include-deps -fincludes-quoted -D /home/vikas/srslte-ric/build/srsenb/src/ric/messages/E2SM-NEXRAN/`
 */

#ifndef	_E2SM_NEXRAN_GUTI_H_
#define	_E2SM_NEXRAN_GUTI_H_


#include "asn_application.h"

/* Including external dependencies */
#include "E2SM_NEXRAN_GUMMEI.h"
#include "E2SM_NEXRAN_M-TMSI.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* E2SM_NEXRAN_GUTI */
typedef struct E2SM_NEXRAN_GUTI {
	E2SM_NEXRAN_GUMMEI_t	 gummei;
	E2SM_NEXRAN_M_TMSI_t	 mtmsi;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2SM_NEXRAN_GUTI_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_E2SM_NEXRAN_GUTI;

#ifdef __cplusplus
}
#endif

#endif	/* _E2SM_NEXRAN_GUTI_H_ */
#include "asn_internal.h"
