/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2AP-IEs"
 * 	found in "../e2ap-v02.03.asn1"
 * 	`asn1c -pdu=all -fcompound-names -fincludes-quoted -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D EXACT/`
 */

#ifndef	_E2AP_CauseRICrequest_H_
#define	_E2AP_CauseRICrequest_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum E2AP_CauseRICrequest {
	E2AP_CauseRICrequest_ran_function_id_invalid	= 0,
	E2AP_CauseRICrequest_action_not_supported	= 1,
	E2AP_CauseRICrequest_excessive_actions	= 2,
	E2AP_CauseRICrequest_duplicate_action	= 3,
	E2AP_CauseRICrequest_duplicate_event_trigger	= 4,
	E2AP_CauseRICrequest_function_resource_limit	= 5,
	E2AP_CauseRICrequest_request_id_unknown	= 6,
	E2AP_CauseRICrequest_inconsistent_action_subsequent_action_sequence	= 7,
	E2AP_CauseRICrequest_control_message_invalid	= 8,
	E2AP_CauseRICrequest_ric_call_process_id_invalid	= 9,
	E2AP_CauseRICrequest_control_timer_expired	= 10,
	E2AP_CauseRICrequest_control_failed_to_execute	= 11,
	E2AP_CauseRICrequest_system_not_ready	= 12,
	E2AP_CauseRICrequest_unspecified	= 13
	/*
	 * Enumeration is extensible
	 */
} e_E2AP_CauseRICrequest;

/* E2AP_CauseRICrequest */
typedef long	 E2AP_CauseRICrequest_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_E2AP_CauseRICrequest_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_E2AP_CauseRICrequest;
extern const asn_INTEGER_specifics_t asn_SPC_CauseRICrequest_specs_1;
asn_struct_free_f CauseRICrequest_free;
asn_struct_print_f CauseRICrequest_print;
asn_constr_check_f CauseRICrequest_constraint;
ber_type_decoder_f CauseRICrequest_decode_ber;
der_type_encoder_f CauseRICrequest_encode_der;
xer_type_decoder_f CauseRICrequest_decode_xer;
xer_type_encoder_f CauseRICrequest_encode_xer;
per_type_decoder_f CauseRICrequest_decode_uper;
per_type_encoder_f CauseRICrequest_encode_uper;
per_type_decoder_f CauseRICrequest_decode_aper;
per_type_encoder_f CauseRICrequest_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _E2AP_CauseRICrequest_H_ */
#include "asn_internal.h"
