/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2AP-IEs"
 * 	found in "../e2ap-v02.03.asn1"
 * 	`asn1c -pdu=all -fcompound-names -fincludes-quoted -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D EXACT/`
 */

#ifndef	_E2AP_AMFName_H_
#define	_E2AP_AMFName_H_


#include "asn_application.h"

/* Including external dependencies */
#include "PrintableString.h"

#ifdef __cplusplus
extern "C" {
#endif

/* E2AP_AMFName */
typedef PrintableString_t	 E2AP_AMFName_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_E2AP_AMFName_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_E2AP_AMFName;
asn_struct_free_f E2AP_AMFName_free;
asn_struct_print_f E2AP_AMFName_print;
asn_constr_check_f E2AP_AMFName_constraint;
ber_type_decoder_f E2AP_AMFName_decode_ber;
der_type_encoder_f E2AP_AMFName_encode_der;
xer_type_decoder_f E2AP_AMFName_decode_xer;
xer_type_encoder_f E2AP_AMFName_encode_xer;
per_type_decoder_f E2AP_AMFName_decode_uper;
per_type_encoder_f E2AP_AMFName_encode_uper;
per_type_decoder_f E2AP_AMFName_decode_aper;
per_type_encoder_f E2AP_AMFName_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _E2AP_AMFName_H_ */
#include "asn_internal.h"
