/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2AP-IEs"
 * 	found in "../e2ap-v02.03.asn1"
 * 	`asn1c -pdu=all -fcompound-names -fincludes-quoted -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D EXACT/`
 */

#ifndef	_E2AP_GlobalE2node_ng_eNB_ID_H_
#define	_E2AP_GlobalE2node_ng_eNB_ID_H_


#include "asn_application.h"

/* Including external dependencies */
#include "E2AP_GlobalngeNB-ID.h"
#include "E2AP_NGENB-DU-ID.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct E2AP_GlobalENB_ID;

/* E2AP_GlobalE2node-ng-eNB-ID */
typedef struct E2AP_GlobalE2node_ng_eNB_ID {
	E2AP_GlobalngeNB_ID_t	 global_ng_eNB_ID;
	struct E2AP_GlobalENB_ID	*global_eNB_ID;	/* OPTIONAL */
	E2AP_NGENB_DU_ID_t	*ngENB_DU_ID;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2AP_GlobalE2node_ng_eNB_ID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_E2AP_GlobalE2node_ng_eNB_ID;
extern asn_SEQUENCE_specifics_t asn_SPC_E2AP_GlobalE2node_ng_eNB_ID_specs_1;
extern asn_TYPE_member_t asn_MBR_E2AP_GlobalE2node_ng_eNB_ID_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _E2AP_GlobalE2node_ng_eNB_ID_H_ */
#include "asn_internal.h"
