/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-COMMON-IEs"
 * 	found in "../E2SM/e2sm-v02.01.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example -fno-include-deps -fincludes-quoted -D E2SM-RC/`
 */

#ifndef	_E2SM_RC_UEID_H_
#define	_E2SM_RC_UEID_H_


#include "asn_application.h"

/* Including external dependencies */
#include "E2SM_RC_UEID-GNB.h"
#include "E2SM_RC_UEID-GNB-DU.h"
#include "E2SM_RC_UEID-GNB-CU-UP.h"
#include "E2SM_RC_UEID-NG-ENB.h"
#include "E2SM_RC_UEID-NG-ENB-DU.h"
#include "E2SM_RC_UEID-EN-GNB.h"
#include "E2SM_RC_UEID-ENB.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum E2SM_RC_UEID_PR {
	E2SM_RC_UEID_PR_NOTHING,	/* No components present */
	E2SM_RC_UEID_PR_gNB_UEID,
	E2SM_RC_UEID_PR_gNB_DU_UEID,
	E2SM_RC_UEID_PR_gNB_CU_UP_UEID,
	E2SM_RC_UEID_PR_ng_eNB_UEID,
	E2SM_RC_UEID_PR_ng_eNB_DU_UEID,
	E2SM_RC_UEID_PR_en_gNB_UEID,
	E2SM_RC_UEID_PR_eNB_UEID
	/* Extensions may appear below */
	
} E2SM_RC_UEID_PR;

/* E2SM_RC_UEID */
typedef struct E2SM_RC_UEID {
	E2SM_RC_UEID_PR present;
	union E2SM_RC_UEID_u {
		E2SM_RC_UEID_GNB_t	 gNB_UEID;
		E2SM_RC_UEID_GNB_DU_t	 gNB_DU_UEID;
		E2SM_RC_UEID_GNB_CU_UP_t	 gNB_CU_UP_UEID;
		E2SM_RC_UEID_NG_ENB_t	 ng_eNB_UEID;
		E2SM_RC_UEID_NG_ENB_DU_t	 ng_eNB_DU_UEID;
		E2SM_RC_UEID_EN_GNB_t	 en_gNB_UEID;
		E2SM_RC_UEID_ENB_t	 eNB_UEID;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2SM_RC_UEID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_E2SM_RC_UEID;
extern asn_CHOICE_specifics_t asn_SPC_E2SM_RC_UEID_specs_1;
extern asn_TYPE_member_t asn_MBR_E2SM_RC_UEID_1[7];
extern asn_per_constraints_t asn_PER_type_E2SM_RC_UEID_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _E2SM_RC_UEID_H_ */
#include "asn_internal.h"
