/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-RC-IEs"
 * 	found in "e2sm-rc-v01.03.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example -fno-include-deps -fincludes-quoted -D E2SM-RC/`
 */

#ifndef	_E2SM_RC_TriggerType_Choice_H_
#define	_E2SM_RC_TriggerType_Choice_H_


#include "asn_application.h"

/* Including external dependencies */
#include "E2SM_RC_TriggerType-Choice-RRCstate.h"
#include "E2SM_RC_TriggerType-Choice-UEID.h"
#include "E2SM_RC_TriggerType-Choice-L2state.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum E2SM_RC_TriggerType_Choice_PR {
	E2SM_RC_TriggerType_Choice_PR_NOTHING,	/* No components present */
	E2SM_RC_TriggerType_Choice_PR_triggerType_Choice_RRCstate,
	E2SM_RC_TriggerType_Choice_PR_triggerType_Choice_UEID,
	E2SM_RC_TriggerType_Choice_PR_triggerType_Choice_L2state
	/* Extensions may appear below */
	
} E2SM_RC_TriggerType_Choice_PR;

/* E2SM_RC_TriggerType-Choice */
typedef struct E2SM_RC_TriggerType_Choice {
	E2SM_RC_TriggerType_Choice_PR present;
	union E2SM_RC_TriggerType_Choice_u {
		E2SM_RC_TriggerType_Choice_RRCstate_t	 triggerType_Choice_RRCstate;
		E2SM_RC_TriggerType_Choice_UEID_t	 triggerType_Choice_UEID;
		E2SM_RC_TriggerType_Choice_L2state_t	 triggerType_Choice_L2state;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2SM_RC_TriggerType_Choice_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_E2SM_RC_TriggerType_Choice;
extern asn_CHOICE_specifics_t asn_SPC_E2SM_RC_TriggerType_Choice_specs_1;
extern asn_TYPE_member_t asn_MBR_E2SM_RC_TriggerType_Choice_1[3];
extern asn_per_constraints_t asn_PER_type_E2SM_RC_TriggerType_Choice_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _E2SM_RC_TriggerType_Choice_H_ */
#include "asn_internal.h"
