/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-COMMON-IEs"
 * 	found in "../E2SM/e2sm-v02.01.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example -fno-include-deps -fincludes-quoted -D E2SM-RC/`
 */

#include "E2SM_RC_UEID.h"

asn_per_constraints_t asn_PER_type_E2SM_RC_UEID_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  3,  3,  0,  6 }	/* (0..6,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_E2SM_RC_UEID_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct E2SM_RC_UEID, choice.gNB_UEID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_E2SM_RC_UEID_GNB,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"gNB-UEID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct E2SM_RC_UEID, choice.gNB_DU_UEID),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_E2SM_RC_UEID_GNB_DU,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"gNB-DU-UEID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct E2SM_RC_UEID, choice.gNB_CU_UP_UEID),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_E2SM_RC_UEID_GNB_CU_UP,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"gNB-CU-UP-UEID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct E2SM_RC_UEID, choice.ng_eNB_UEID),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_E2SM_RC_UEID_NG_ENB,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ng-eNB-UEID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct E2SM_RC_UEID, choice.ng_eNB_DU_UEID),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_E2SM_RC_UEID_NG_ENB_DU,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ng-eNB-DU-UEID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct E2SM_RC_UEID, choice.en_gNB_UEID),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_E2SM_RC_UEID_EN_GNB,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"en-gNB-UEID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct E2SM_RC_UEID, choice.eNB_UEID),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_E2SM_RC_UEID_ENB,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"eNB-UEID"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_E2SM_RC_UEID_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* gNB-UEID */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* gNB-DU-UEID */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* gNB-CU-UP-UEID */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* ng-eNB-UEID */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* ng-eNB-DU-UEID */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* en-gNB-UEID */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 } /* eNB-UEID */
};
asn_CHOICE_specifics_t asn_SPC_E2SM_RC_UEID_specs_1 = {
	sizeof(struct E2SM_RC_UEID),
	offsetof(struct E2SM_RC_UEID, _asn_ctx),
	offsetof(struct E2SM_RC_UEID, present),
	sizeof(((struct E2SM_RC_UEID *)0)->present),
	asn_MAP_E2SM_RC_UEID_tag2el_1,
	7,	/* Count of tags in the map */
	0, 0,
	7	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_E2SM_RC_UEID = {
	"UEID",
	"UEID",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, &asn_PER_type_E2SM_RC_UEID_constr_1, CHOICE_constraint },
	asn_MBR_E2SM_RC_UEID_1,
	7,	/* Elements count */
	&asn_SPC_E2SM_RC_UEID_specs_1	/* Additional specs */
};

