/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 */

#ifndef _E2SM_RC_ASN_CONSTANT_H
#define _E2SM_RC_ASN_CONSTANT_H

#ifdef __cplusplus
extern "C" {
#endif

#define E2SM_RC_maxnoofMessages (65535)
#define E2SM_RC_maxnoofE2InfoChanges (65535)
#define E2SM_RC_maxnoofUEInfoChanges (65535)
#define E2SM_RC_maxnoofRRCstate (8)
#define E2SM_RC_maxnoofParametersToReport (65535)
#define E2SM_RC_maxnoofPolicyConditions (65535)
#define E2SM_RC_maxnoofAssociatedRANParameters (65535)
#define E2SM_RC_maxnoofUEID (65535)
#define E2SM_RC_maxnoofCellID (65535)
#define E2SM_RC_maxnoofRANOutcomeParameters (255)
#define E2SM_RC_maxnoofParametersinStructure (65535)
#define E2SM_RC_maxnoofItemsinList (65535)
#define E2SM_RC_maxnoofUEInfo (65535)
#define E2SM_RC_maxnoofCellInfo (65535)
#define E2SM_RC_maxnoofUEeventInfo (65535)
#define E2SM_RC_maxnoofRANparamTest (255)
#define E2SM_RC_maxnoofNeighbourCell (65535)
#define E2SM_RC_maxnoofRICStyles (63)
#define E2SM_RC_maxnoofCallProcessTypes (65535)
#define E2SM_RC_maxnoofCallProcessBreakpoints (65535)
#define E2SM_RC_maxnoofInsertIndication (65535)
#define E2SM_RC_maxnoofControlAction (65535)
#define E2SM_RC_maxnoofPolicyAction (65535)
#define E2SM_RC_maxnoofInsertIndicationActions (63)
#define E2SM_RC_maxnoofMulCtrlActions (63)
#define E2SM_RC_maxE1APid (65535)
#define E2SM_RC_maxF1APid (4)
#define E2SM_RC_maxEARFCN (65535)
#define E2SM_RC_maxNRARFCN (3279165)
#define E2SM_RC_maxnoofNrCellBands (32)


#ifdef __cplusplus
}
#endif

#endif /* _E2SM_RC_ASN_CONSTANT_H */
